### ISSUE TITLE
Issue with Checkmate_FPS_FT.ovl

### ISSUE THREAD

**Issue by cSharpieDart** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#1]
The .ovl does not display the same as your screenshot in the guide. It only shows fps

**Comment by sirstonie** [comment]
In the general setting of Hwinfo you need to check the shared memory support. Then it should show up in rtss

**Comment by baldsealion** [comment]
I would check a couple items:
1. Make sure you installed HWiNFO -- then copied over the portable beta version
2. Make sure you import the HWiNFO registry file while HWiNFO is closed

**Comment by cSharpieDart** [comment]
![16671956375574317683053978106406](https://user-images.githubusercontent.com/53220846/198940828-939205ed-1ef4-4b4d-8d67-ac03126f3bc6.jpg)

I've attached a screenshot of how it is appearing for me. 1 and 2 have both been done correctly. Also enabling shared memory support does not fix this either

**Comment by jpin79** [comment]
I have the same problem

**Comment by baldsealion** [comment]
Thanks, I just wiped my SteamDeck and plan on testing this today/tonight. I will report back.

**Comment by jpin79** [comment]
Thanks. It may be too much to ask but do you think that you could record and post the whole 1.6 process? If not, thanks anyway.

**Comment by baldsealion** [comment]
Sorry, I already worked on it before I saw that comment so I didn't record, but it worked perfectly fine. An additional user in the SteamDeck Discord said he encountered the same issue, then he re-did it and everything works for him. So it's definitely a user-process issue.

Please re-download the .ovl file, it should be called "Naptha.ovl"

I added some more verbiage to make it easier to understand hopefully. You need to make sure that HWiNFO is running in your Taskbar, if you close it, it does not minimize the application.

Once you have all that and re-import the Naptha.ovl to the correct folder, make sure that you check the Layout Editor and it should look like the guide. 

Please re-follow the steps.
