### ISSUE TITLE
CRU black screen on 720p - How Remove/Replace steam deck EDID in windows

### ISSUE THREAD

**Issue by Sfree4ever** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#10]
Hi, in your guide I used CRU and imported the bin with custom resolution and refresh rate, refresh rate works fine (30hz gives slight flickering due to the screen type of deck), but the problem is with resolution, when I change to custom resolution to 720p in advanced display settings > all modes,  I get black screen and this doesn't fix the problem with most games detecting screen native/max resolution EDID, and giving problems in exclusive fullscreen mode, because of aspect ratio/resolution not supported, things like black screen, or squashed image with very low resolution happens in many console ports, or japanese games/rpgs. In those games I need to use window or borderless, but performance takes a hit sometimes.

To fix this I need to change EDID to 16:9  720p, I noticed in your files you have "ciphray_deck_edid_remove.bat" and "Checkmate_AIO_WIP4_EDID.zip"

In your ultimate guide you don't mention how to replace EDID, could you please explain or add to the guide how to use those files and replace EDID to 720p, so that many games will stop having problems with the 16:10? I can alway revert the EDID to original for games that fully support 16:10, right?

Btw I'm still using windows 10, when I found your guide already had installed many games, but should work basically the same.

Thanks alot for your guide and your support.

**Comment by baldsealion** [comment]
There is no real special fix for exclusive fullscreen. 

If you use the "Checkmate 720..." bin file inside of the repo folder, you will be able to use 720p in exclusive full screen but it will have a big black bar on the top of the screen.

To change the binaries you just import the new one with CRU, it will overwrite the old values. I don't have a copy of the original binary at this time, but to fully revert you can also do an APU driver reinstall with the factory reset option checked.

Also, you can use GPU Scaling with AMD Adrenaline or Steam Deck Tools to set lower custom resolutions, this might work for some games with fullscreen, but is experimental. 

The goal really instead is to avoid exclusive fullscreen at all costs. If the game can only do a windowed mode, use borderless gaming or lossless scaling(app on steam) to maximize it into a borderless window.

**Comment by baldsealion** [comment]
Some games will simply override refresh rate, they were meant to always run at 60 then, it's definitely not a perfect system, but some games also rely on the 60hz for the physics of the game.

For the vertical screen issue, I have seen that but usually, you would run it in a window and use lossless scaling and it would stretch it back into shape. If the game is exclusive fullscreen only, then it is a tougher battle, like maybe using dxwnd to force it into a windowed mode, then use lossless scaling to fill the screen. 

I am guessing some of these games are pretty old if they don't have a windowed option.
