### ISSUE TITLE
Automatic Double Click 

### ISSUE THREAD

**Issue by seavers11** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#11]
I install windows 11 step by step like written in the tutorial.

When I start steam in gamepadui i got a double click when i use the digipad or the other keys like A,B,Y,X

Someone else ?

**Comment by baldsealion** [comment]
Did you choose to use it with the Controller app with Steam Input? If you have it set to "Ignore Steam", then you will get double inputs. 

Also, Ayufan just released a new version of Steam Deck Tools that addresses some Steam Input issues on the latest version of the Steam Client.

**Comment by seavers11** [comment]
Hello,

i tried all controller options but always the same here.

I will try the new version and see if it works, thanks for your answer and
help, and the great tutorial 👍

I got a second problem, when i for example open the browser, the text are
very blurry and thin and it is very difficult to read something, do you
have an idea which app or setting are the reason for that ?

thx

Marc

baldsealion ***@***.***> schrieb am Di., 31. Jan. 2023, 20:58:

**Comment by seavers11** [comment]
I update to version 0.6.7 but when in gamepadui in the steam menu where you can select downloads, Bibliothek, Shop etc when I press the digipad or the buttons they always make a double input, outside from this menu it works fine ?

**Comment by baldsealion** [comment]
I would post the issue on Ayufan's Github for Steam Deck Tools. 

* [https://github.com/ayufan/steam-deck-tools/issues](url)
