### ISSUE TITLE
Easy Switching Between 40 Hz And 60 Hz Refresh Rates After Unlocking

### ISSUE THREAD

**Issue by Adravil** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#13]
Good day and thanks for your contribution!

Here is the suggestion to expand the section [1.5 Unlocking Refresh Rate & RTSS](https://github.com/baldsealion/Steamdeck-Ultimate-Windows11-Guide/wiki/1.5-Unlocking-Refresh-Rate-&-RTSS#unlocking-refresh-rates) with batches made for easy switching between 40 Hz and 60 Hz modes. The template below is, hopefully, ready to use by your quality standards. If not -- ping me and I will drop a PR, for example. Or, here is literally the source code of this comment's main part:
[source code of the comment.txt](https://github.com/baldsealion/Steamdeck-Ultimate-Windows11-Guide/files/10774062/source.code.of.the.comment.txt)

Holy cow how hungry am I after polishing all of this 😂.

**Easy Switching Between 40 Hz And 60 Hz Refresh Rates After Unlocking**
----------------------------
1. Download **[NirCmd](https://www.nirsoft.net/utils/nircmd.html)**, extract somewhere you will permanently keep (Ex: _C:\\\<Username>\Documents\Tools\nircmd-64_):
- [NirCmd by Nir Sofer](https://www.nirsoft.net/utils/nircmd-x64.zip)
- [The entire list of commands, supported by NirComd, if you feel adventurous today](http://nircmd.nirsoft.net/)
2. Download the next archive, extract files somewhere you will permanently keep (Ex: _C:\\\<Username>\Documents\Tools\nircmd-64\40.bat_ _C:\\\<Username>\Documents\Tools\nircmd-64\60.bat_):
- [40+60 by Adravil.zip](https://github.com/baldsealion/Steamdeck-Ultimate-Windows11-Guide/files/10774013/40%2B60.by.Adravil.zip)
You are free to rename these two files from the archive after extraction and create shortcuts for them as for any other files.
3. Do not run the _40.bat_ file yet (via double click). Open it with any notepad you have for editing instead. You will see the next text:
`cmd /c "C:\<Username>\Documents\Tools\nircmd-64\nircmd.exe" setdisplay 1280 800 32 40`
4. In that file, replace the
`"C:\<Username>\Documents\Tools\nircmd-64"`
part with the path you saved NirCmd at.
- For example, if you saved NirCmd at _C:\DefinitelyNotTheSwitchEmulatorHappyOwner\Documents\Tools\nircmd-64_
the contents of your _40.bat_ file should be replaced with
`cmd /c "C:\DefinitelyNotTheSwitchEmulatorHappyOwner\Documents\Tools\nircmd-64\nircmd.exe" setdisplay 1280 800 32 40`
5. Save the changes.
6. Repeat Steps 3, 4 and 5 for the _60.bat_ file.
7. Now, if you have done everything right, double-clicking the _40.bat_ file will do all the magic for you, and switch the refresh rate of your Steam Deck's display adapter to 40 Hz. And double-clicking the _60.bat_ file will return it back to 60 Hz.
- Feel free to add more files like this to switch to other display adapter profiles if you wish. **bat** extension is the same **txt**, that's why any notepad understands it. Extensions can be shown to the user by enabling the respective option under Win10's `File Explorer > View tab > File name extensions`. Profiles can be found under Win10's: `Settings > System > Display > Advanced display settings > Display adapter properties for Display <some number> > List All Modes`
8. Take care of your Steam Deck as much as of yourself, and you both will live a long happy life.

**Comment by baldsealion** [comment]
Hi,

Thanks for the feedback and detailed suggestion. This was actually the initial process for the most part. We had an AutoHotKey script that would call Nircmd for Refresh Rate setting and RyzenADJ for TDP. This was then also configured as Hotkeys with SWICD. You can see the file still here in the repo, it's just omitted from the instructions:

[https://github.com/baldsealion/Steamdeck-Ultimate-Windows11-Guide/tree/main/AutoHotKey_Scripts](url)

This was scrapped once Steam Deck Tools came along. The PowerControl app does all of this without additional configuration.
