### ISSUE TITLE
New Wiki seems no longer accessible?

### ISSUE THREAD

**Issue by ikari7789** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#15]
Accessing https://baldsealion.github.io/Steam-Deck-Ultimate-Windows-Guide/ leads to a 404 error?

**Comment by ikari7789** [comment]
Thank you!

I did manage to find the https://badsealion.com page after some digging. May be best to update the MegaThread on the WindowsForSteamdeck subreddit, which still points to the broken link.

Also, would like to note that the gh-pages implementation seems to be using a non-standard file naming scheme, which fails to load the top page as it isn't `index.html`.

https://baldsealion.github.io/PC-Handheld-Guides/Steam-Deck-Ultimate-Windows-Guide/MAIN.html

**Comment by baldsealion** [comment]
Thank you I will look into this
