### ISSUE TITLE
Debloating windows 11

### ISSUE THREAD

**Issue by Milio1985** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#2]
Hey. Thank you for the work in that Guide. You mentioned that if there is a good way to debloat win11 with revert changues posibility you take a look on. Ok i think this is a good way:
https://youtu.be/8ReoMuCUdKE
I'm not sure at all, but you can check and Share your  opinion about if it is a good way to achieve.

**Comment by baldsealion** [comment]
Thanks, I think I'll include as an optional suggestion, he's a little bit "wordy", in that all of his videos, he talks a lot for fluff, like he spends the first 8 minutes ranting about Microsoft-- but there is some good content in there.
