### ISSUE TITLE
Problem with trackpad and SWICD config

### ISSUE THREAD

**Issue by preacha** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#4]
Hello,

thank you for this awesome Guide.
I followed now everything to point 1.4 SWICD Configuration but i get the following error and it seems like the trackpads are not working:
![Error SWICD](https://user-images.githubusercontent.com/7067861/203295663-91cccb57-5855-420c-8e42-8d16e46d42fc.png)
Any ideas?
I have updated to Win11 22H2 yesterday. Maybe this could cause the problem? But so far I have not noticed any other errors

**Comment by preacha** [comment]
OK i should have read this before: Mouse Movement Enabled should be unchecked and Buttons Disabled should be checked already) but it was not unchecked altough i have copied the profile in the path that was mentioned before.

**Comment by ajridgway** [comment]
Out of interest what's the benefit of disabling the trackpad or the rationale?  

Thank you for an awesome guide BTW
