### ISSUE TITLE
Tetherscript link not working

### ISSUE THREAD

**Issue by andrewbaker-uk** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#5]
The Tetherscript download link in section 1.4 is now returning ERR_CONNECTION_TIMED_OUT and for the root domain

**Comment by baldsealion** [comment]
This is the second time the Tetherscript site has gone down.

I have uploaded all downloads necessary into one zip file for 1.4 Controller Configuration section- can be obtained directly here https://pixeldrain.com/u/HhUDEzvE
