### ISSUE TITLE
Suggestion to resolve issues navigating start menu and windows settings

### ISSUE THREAD

**Issue by hJdTzv7G** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#7]
For me, when navigating the pinned apps in the start menu with the d-pad, each press moves the selection box 2 icons in a direction instead of 1.

Also, when in the Display page of Settings, when I move the scroll bar halfway down, the scroll bar moves all the way down, and when I try to scroll up, the scroll bar is continually forced back down.

This only happens for me when SWICD is open so my guess is that it's happening because SWICD exposes an xbox controller input to the system and UWP apps (e.g. start menu, settings) translate xbox controller inputs to keyboard mappings.

I searched online and found that people who used windows with a controller had issues like this too and this regedit change fixed it for me (fix: https://gist.github.com/Susko3/a59aace42579222e351e57abfad0cef5, context: https://github.com/microsoft/microsoft-ui-xaml/issues/1495)

Just wanted to share that discovery in hopes that it helps others using Steam Deck and Windows 11.

Feel free to close this issue and please take this as just a suggestion.

**Comment by baldsealion** [comment]
SWICD is considered legacy at this point -- no longer updating anything related to guide for it. Now using SteamController app in Steam Deck Tools.
