### ISSUE TITLE
Suggestion to mention option to make L2 mouse left click and R2 mouse right click (instead of the default which is the other way around)

### ISSUE THREAD

**Issue by hJdTzv7G** [baldsealion/Steamdeck-Ultimate-Windows11-Guide#8]
Just another suggestion that was helpful for me.

By default R2 is left click and L2 is right click but I prefer the opposite. I was able to change this with the following:

Settings > Bluetooth & devices > Mouse > Additional mouse settings > Switch primary and secondary buttons (default is disabled and I set it to enabled).

I also confirmed that it worked with Steam Deck Tools's SteamController shortcuts and does not swap L2 and R2 when in game.

**Comment by baldsealion** [comment]
Interesting preference! I think for dual-boot purposes, it's best to stay with the default settings that mirror SteamOS configuration, so I will not include this in the guide.
